# Generated by Django 5.2.9 on 2025-12-07 00:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Cod. Radar')),
                ('title', models.CharField(max_length=64, verbose_name='Tit. Radar')),
                ('description', models.CharField(max_length=64, verbose_name='Descrip.')),
                ('center_lat', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud centro')),
                ('center_long', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud centro')),
                ('img_radio', models.IntegerField(choices=[(120, '120km'), (240, '240km'), (480, '480km')], verbose_name='Rádio de la Imagen (kmts)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Radar activo?')),
                ('point1_lat', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=14, verbose_name='Latitud Norte')),
                ('point1_long', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=14, verbose_name='Longitud Este')),
                ('point2_lat', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=14, verbose_name='Latitud Sur')),
                ('point2_long', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=14, verbose_name='Longitud Oeste')),
            ],
            options={
                'verbose_name': 'Radar',
                'verbose_name_plural': 'Radares',
            },
        ),
        migrations.CreateModel(
            name='RadarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(default='', max_length=10, verbose_name='Código de Producto (Nombre de la imagen)')),
                ('product_title', models.CharField(default='', max_length=10, verbose_name='Título de Producto')),
                ('product_description', models.TextField(default='', verbose_name='Descripción de Producto')),
                ('enabled', models.BooleanField(default=True, verbose_name='Se muestra?')),
                ('see_in_open', models.BooleanField(default=False, verbose_name='Mostrar al inicio')),
            ],
            options={
                'verbose_name': 'Producto de Radar',
                'verbose_name_plural': 'Productos de Radar',
                'ordering': ['product_key'],
            },
        ),
        migrations.CreateModel(
            name='Volumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Volumen',
                'verbose_name_plural': 'Volumenes',
            },
        ),
        migrations.CreateModel(
            name='RadarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='radares/images')),
                ('polarimetric_var', models.CharField(default='', max_length=10, verbose_name='Variable Polarimétrica')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('strategy', models.IntegerField(default=0, verbose_name='Estrategia')),
                ('scanning', models.IntegerField(default=0, verbose_name='Num. Barrido')),
                ('sweep', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Ángulo de la elevacion')),
                ('show_me', models.BooleanField(default=True, verbose_name='Se muestra?')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='radar_api.radar')),
            ],
            options={
                'verbose_name': 'Imagen de Radar',
                'verbose_name_plural': 'Imagenes de Radares',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='Referencia')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripción')),
                ('unit', models.CharField(default='', max_length=64, verbose_name='Unidad')),
                ('value', models.FloatField(default=0, verbose_name='Valor')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color (RGB con # al principio)')),
                ('color_font', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de texto (RGB con # al principio)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='radar_api.radarproduct')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='ID de Estrategia')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripción')),
                ('volumenes', models.ManyToManyField(related_name='estrategias', to='radar_api.volumen')),
            ],
            options={
                'verbose_name': 'Volumen',
                'verbose_name_plural': 'Estrategias',
            },
        ),
    ]
