"""
Models for radar_viewer application.

Stores metadata about radar products for visualization.
"""

from django.db import models


class RadarProduct(models.Model):
    """
    Model representing a radar product generated by genpro25.
    """
    
    PRODUCT_TYPES = [
        ('PPI', 'Plan Position Indicator'),
        ('CAPPI', 'Constant Altitude PPI'),
        ('RHI', 'Range Height Indicator'),
        ('COMPOSITE', 'Composite Product'),
    ]
    
    name = models.CharField(max_length=255)
    product_type = models.CharField(max_length=20, choices=PRODUCT_TYPES)
    file_path = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    valid_time = models.DateTimeField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    elevation = models.FloatField(null=True, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    
    class Meta:
        ordering = ['-valid_time']
        verbose_name = 'Radar Product'
        verbose_name_plural = 'Radar Products'
    
    def __str__(self):
        return f"{self.name} - {self.product_type} ({self.valid_time})"


class RadarStation(models.Model):
    """
    Model representing a radar station.
    """
    
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    altitude = models.FloatField()
    is_active = models.BooleanField(default=True)
    
    class Meta:
        verbose_name = 'Radar Station'
        verbose_name_plural = 'Radar Stations'
    
    def __str__(self):
        return f"{self.code} - {self.name}"
